only bother with leaf nodes, smaller but slower? (#12)
also error message when package not found
also correctly prepend $PREFIX on reverse mode

diff --git a/whatprovides b/whatprovides
--- a/whatprovides
+++ b/whatprovides
@@ -116,9 +116,17 @@ if ${REVERSE_MODE}; then
 		exit 1
 	fi
 
-	sqlite3 "${DB_PATH}" \
+	if ! sqlite3 "${DB_PATH}" \
 		"SELECT owned_file FROM 'whatprovides' WHERE package_name == '${1}' ORDER BY owned_file" \
-		| awk "NR == 1 { print \"${1}: /.\\n${1}: /data\\n${1}: /data/data\\n${1}: /data/data/com.termux\\n${1}: /data/data/com.termux/files\\n${1}: ${PREFIX}\" } { print \"${1}: ${PREFIX}/\"\$0 }"
+		| awk "{ if (substr(\$0, 1, 1) == \"/\") print \"${1}: \"\$0; else print \"${1}: ${PREFIX}/\"\$0 } END { if (NR == 0) exit 1 }"
+	then
+		{
+			echo
+			echo "Error: package '$1' is not found."
+			echo
+		} >&2
+		exit 1
+	fi
 else
 	NEWPREFIX=
 	FILE="$(realpath -sm "$1")"
@@ -141,8 +149,9 @@ else
 		NEWPREFIX="${PREFIX}/"
 	fi # else FILE is entirely separate from PREFIX (unlikely to be in DB)
 
+	FILE_ESC="${FILE//\'/\'\'}"
 	if ! sqlite3 "${DB_PATH}" \
-		"SELECT package_name FROM 'whatprovides' WHERE owned_file == '${FILE//\'/\'\'}' ORDER BY package_name" \
+		"SELECT DISTINCT package_name FROM 'whatprovides' WHERE owned_file == '${FILE_ESC}' OR substr(owned_file, 1, ${#FILE} +1) == '${FILE_ESC}/' ORDER BY package_name" \
 		| awk "{ print \$0\": ${NEWPREFIX}${FILE}\" } END { if (NR == 0) exit 1 }"
 	then
 		{
